version: "3.5"

services:
  postgres:
    container_name: projetobd-postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-projetobd}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-projetobd}
      POSTGRES_DB: projetobd
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./scripts/sql/banco_de_dados.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    networks:
      - projetobd
    restart: unless-stopped

  # http://localhost:5050
  pgadmin:
    container_name: projetobd-pgadmin
    image: dpage/pgadmin4
    user: $UID:$GID
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-projetobd}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
      # - ./:/shared
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - projetobd
    restart: unless-stopped

networks:
  projetobd:
    driver: bridge

volumes:
  postgres:
  pgadmin:
